### ISSUE TITLE
 undefined reference to symbol 'XConvertSelection'

### ISSUE THREAD

**Issue by 4444jw4444** [ataiya/dgp#4]
Attempting to get the project to build on Ubuntu 14.04.

Cannot complete a build of the dgp project inside of QTCreator without errors:

15:38:40: Running steps for project dgp...
15:38:40: Starting: "/usr/bin/make" all
[ 14%] Built target lab01_eigen
Linking CXX executable lab01_triangle
/usr/bin/ld: /usr/local/lib/libglfw3.a(x11_window.c.o): undefined reference to symbol 'XConvertSelection'
/usr/lib/x86_64-linux-gnu/libX11.so.6: error adding symbols: DSO missing from command line
lab01_triangle/CMakeFiles/lab01_triangle.dir/build.make:89: recipe for target 'lab01_triangle/lab01_triangle' failed
CMakeFiles/Makefile2:202: recipe for target 'lab01_triangle/CMakeFiles/lab01_triangle.dir/all' failed
Makefile:75: recipe for target 'all' failed
collect2: error: ld returned 1 exit status
make[2]: *** [lab01_triangle/lab01_triangle] Error 1
make[1]: *** [lab01_triangle/CMakeFiles/lab01_triangle.dir/all] Error 2
make: *** [all] Error 2
15:38:40: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project dgp (kit: Desktop)
When executing step "Make"
15:38:40: Elapsed time: 00:00.

Process:
Note: Before performing the installation setup for dgp I was able to run the icg projects that I did last semester no problem. After performing the following steps I get this error: undefined symbol: glfwOpenWindowHint. 

1. Installed all required packages as specified here : [https://github.com/ataiya/dgp/wiki/Compiling-in-Linux](url) 
2. Compiled GLFW3 as specified here: [http://www.glfw.org/docs/latest/compile.html](url) using cmake and qtcreator
3. try to build the dgp project and get the above error. Screen shot attached. 
![screenshot from 2016-01-31 15-54-15](https://cloud.githubusercontent.com/assets/10537446/12706128/ead63900-c832-11e5-9f8a-618b7c1c53f6.png)

Any help is much appreciated
Jorin

**Comment by ataiya** [comment]
Why not just use the glfw3 that comes with the OS rather than re-compiling it by hand? (from apt-get)

**Comment by ataiya** [comment]
This seems relevant: 
http://stackoverflow.com/questions/24345384/glfw-linker-errors-on-ubuntu-14-04-lts

**Comment by ataiya** [comment]
4444jw4444 did you fix the issue?

**Comment by 4444jw4444** [comment]
This issue is unresolved. The processes above broke the glfw3 packages, and I was forced to reinstall ubuntu. I reinstalled all packages for dgp, and used aptget for each of them. In this case I am unable to open the project in qt because cmake had errors finding the package. This is because cmake has changed its path finding behavior, but glfw3 isnt up to date. It would be necessary to modify the glfw cmake files to accomodate different pathing behaviour. 

At least that is what I think it is.

**Comment by 4444jw4444** [comment]
You can find stack overflow conversations about this issue pretty easily.

**Comment by ataiya** [comment]
> It would be necessary to modify the glfw cmake files to accomodate different pathing behaviour. 

Note that the glfw3 finder was not pre-packaged, we had to write our own. In the ```cmake/``` folder there is a file called FindGLFW3.cmake. This is what (a part of it) looks like:

```
FIND_LIBRARY( GLFW3_LIBRARIES NAMES glfw3 PATHS
    $ENV{GLFWDIR}/lib
    $ENV{GLFWDIR}/support/msvc80/Debug
    $ENV{GLFWDIR}/support/msvc80/Release
    /usr/local/lib
    /usr/local/X11R6/lib
    /usr/X11R6/lib
    /usr/X11/lib
    /usr/lib/X11
    /usr/lib
    /opt/X11/lib
    /opt/lib )
```

On linux, the program simply checks for a file called ```libglfw3.so``` in the listed paths. If your glfw3 library has been installed elsewhere (check apt-get info), you can simply modify the file and add the correct paths. *hint: you might want to trash the build folder, sometimes cmake gets confused.*

**Comment by 4444jw4444** [comment]
Okay, so I found the paths to the packages, included them in the above FIND_LIBRARY function, and still the same error occurs. 


Process:


1. Find paths:
:~$ dpkg -L libglfw3
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/libglfw3
/usr/share/doc/libglfw3/copyright
/usr/share/doc/libglfw3/changelog.Debian.gz
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libglfw.so.3.1
/usr/lib/x86_64-linux-gnu/libglfw.so.3


2. Edit function:
FIND_LIBRARY( GLFW3_LIBRARIES NAMES glfw3 PATHS
    $ENV{GLFWDIR}/lib
    $ENV{GLFWDIR}/support/msvc80/Debug
    $ENV{GLFWDIR}/support/msvc80/Release
    /usr/local/lib
    /usr/local/X11R6/lib
    /usr/X11R6/lib
    /usr/X11/lib
    /usr/lib/X11
    /usr/lib
    /opt/X11/lib
    /opt/lib 
    /usr
    /usr/share
    /usr/share/doc
    /usr/share/doc/libglfw3
    /usr/share/doc/libglfw3/copyright
    /usr/share/doc/libglfw3/changelog.Debian.gz
    /usr/lib
    /usr/lib/x86_64-linux-gnu
    /usr/lib/x86_64-linux-gnu/libglfw.so.3.1
    /usr/lib/x86_64-linux-gnu/libglfw.so.3 )


3. Error in QT creator cmake output:
    CMake Warning at cmake/ConfigureGLFW3.cmake:8 (message):
    GLFW3 not found
    Call Stack (most recent call first):
    CMakeLists.txt:22 (include)


In step 2, the bottom three paths I believe are the direct library paths? The strange thing is that if I use the "whereis" or "which" commands to try and find libglfw3 or glfw3 I get no paths. But "dpkg -L libglfw3" gets a path. And when I "sudo apt-get install libglfw3" I get a notice saying that it is already installed and no updates can occur since it is up to date. I have tried shuffling the path order in the FIND function to search the new paths first, still nothing. I have deleted the dgp-build folder before I do all these steps, and between attempts to make sure cmake isn't being silly.

**Comment by 4444jw4444** [comment]
I have also tried removing all extra/additional features from QT creator using the Ubuntu software centre , checked that QT is up to date, and even tried turning my computer on and off again.

**Comment by ataiya** [comment]
As you are working on your home computer is very difficult for me to help you fix this. I think the issue is that you don't have a "libglfw.so" (you'd have to manually create the symlink).

What you can do is simply replace the "FIND_LIBRARY" command with a single set command. 
If you know the exact path of the library, everything should work out:

```
set(GLFW3_LIBRARIES "/usr/lib/x86_64-linux-gnu/libglfw.so.3")
```

**Comment by 4444jw4444** [comment]
Explicitly setting the path as you directed has solved the issue!! Thank you very much!
